name: Deploy AWS Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build shadow jar
        run: ./gradlew clean shadowJar

      - name: Deploy Lambda
        uses: aws-actions/aws-lambda-deploy@v2
        with:
          function-name: ${{ secrets.LAMBDA_NAME }}
          region: ${{ secrets.AWS_REGION }}
          jar-file: build/libs/send-email-function-0.0.1-SNAPSHOT-all.jar
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}